apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: agn-alerts
spec:
  groups:
    - name: agn-app
      rules:
        - alert: HighErrorRate
          expr: |
            rate(http_error_total[5m]) / rate(http_request_duration_ms_count[5m]) > 0.1
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Error rate over 10%"

        - alert: WorkerStalled
          expr: |
            rate(process_cpu_seconds_total{job="agn-worker"}[2m]) == 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Worker stalled for over 2 minutes"

        - alert: PodCrashLooping
          expr: |
            rate(kube_pod_container_status_restarts_total[15m]) > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod is CrashLooping: {{ $labels.pod }}"