apiVersion: v1
kind: Service
metadata:
  name: agn-api-svc
  labels:
    app: agn-api
spec:
  selector:
    app: agn-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort