apiVersion: apps/v1
kind: Deployment
metadata:
  name: agn-worker
spec:
  replicas: 2       
  selector:
    matchLabels:
      app: agn-worker
  template:
    metadata:
      labels:
        app: agn-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: agn-worker
          image: ghcr.io/settawuts/agn-app/agn-app-worker:latest

          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: NODE_ENV
              value: "production"

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

          livenessProbe:
            exec:
              command:
                - node
                - -e
                - "process.exit(0)"
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3