FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY src/worker/worker.js ./src/worker/worker.js

FROM node:20-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/src/worker/worker.js ./src/worker/worker.js

CMD ["node", "src/worker/worker.js"]